[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "IMUtils_alsmeirelles"
version = "0.0.1"
authors = [
  { name="André L.S. Meirelles", email="alsmeirelles@gmail.com" },
]
description = "A Helper to deal with images and training data"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"