[tool.poetry]
name = "IMUtils"
version = "0.0.1"
readme = "README.md"
packages = [{include = "IMUtils", from = "src"}]
authors = ["André L.S. Meirelles <alsmeirelles@gmail.com>"]
description = "A Helper to deal with images and training data"

[tool.poetry.dependencies]
python = "^3.9"
opencv-python = "^4.5.3.56"
numpy = "^1.26"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

#[build-system]
#requires = ["hatchling"]
#build-backend = "hatchling.build"

[project]
name = "IMUtils"
version = "0.0.1"
readme = "README.MD"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/alsmeirelles/IMUtils"
Issues = "https://github.com/alsmeirelles/IMUtils/issues"